version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - my_network

  backend:
    build: ./backend
    container_name: node_backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: testdb
    depends_on:
      - db
    networks:
      - my_network

  frontend:
    build: ./frontend
    container_name: next_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network

  nginx:
    build: ./nginx
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
